# Learn more: https://shopify.dev/docs/apps/build/cli-for-apps/app-configuration
name = "Zernio"
client_id = "ee20ee832fea8bfbc7fe61e1c960b935"
application_url = "https://zernio-shopify-one.vercel.app"
embedded = true

[auth]
redirect_urls = [
  "https://zernio-shopify-one.vercel.app/auth/callback",
  "https://zernio-shopify-one.vercel.app/auth/shopify/callback",
]

[access_scopes]
scopes = "read_products"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes-update"

  # Mandatory GDPR compliance webhooks
  [[webhooks.subscriptions]]
  uri = "/webhooks/compliance"
  compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
